@baseUrl = http://127.0.0.1:8000

GET {{baseUrl}}/setup

###

GET {{baseUrl}}

###

POST  {{baseUrl}}/sign-up



###

GET {{baseUrl}}/users/1


###
GET {{{{baseUrl}}}}/test

POST {{baseUrl}}/deel

###

POST {{baseUrl}}/sign-up
Content-Type: application/json

{
    "email": "lokesh@12gmail.com",
    "name": "lokesh",
    "password":"lokesh@123"
}

###

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "lokesh@1212gmail.com",
    "password":"lokesh@123"
}

