@baseUrl = http://127.0.0.1:8000

GET {{baseUrl}}/setup

###

GET {{baseUrl}}

###

GET {{baseUrl}}/users

###

GET {{baseUrl}}/users/1


###

POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "deepak@gmail.com",
    "name": "Deepak"
}

