services: 
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    container_name: ecommerce_users_container
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

volumes: 
  pg_data:
  