FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

RUN pip install --upgrade fastapi fastapi-utils

COPY . .

# CMD ["alembic", "upgrade", "head", "&&", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

CMD ["sh", "-c", "alembic revision --autogenerate -m \"Update tables\" && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
